export const notificationData = {
  users: [
    {
      id: 1,
      fullName: 'John Smith',
      username: 'johnsmith',
      email: 'johnsmith@example.com',
      avatarUrl: '',
      title: 'Graphic Designer',
      location: 'New York, NY',
      links: {
        website: 'https://johnsmith.com',
        twitter: 'https://twitter.com/johnsmith',
        instagram: 'https://instagram.com/johnsmith',
        linkedIn: 'https://linkedin.com/in/johnsmith',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 2,
      fullName: 'John Garcia',
      username: 'johngarcia',
      email: 'johngarcia@example.com',
      avatarUrl: '',
      title: 'Product Manager',
      location: 'San Francisco, CA',
      links: {
        website: 'https://johngarcia.com',
        twitter: 'https://twitter.com/johngarcia',
        instagram: 'https://instagram.com/johngarcia',
        linkedIn: 'https://linkedin.com/in/johngarcia',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 3,
      fullName: 'Bob Smith',
      username: 'bobsmith',
      email: 'bobsmith@example.com',
      avatarUrl: '',
      title: 'Graphic Designer',
      location: 'Sao Paulo, Brazil',
      links: {
        website: 'https://bobsmith.com',
        twitter: 'https://twitter.com/bobsmith',
        instagram: 'https://instagram.com/bobsmith',
        linkedIn: 'https://linkedin.com/in/bobsmith',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 4,
      fullName: 'Mike Smith',
      username: 'mikesmith',
      email: 'mikesmith@example.com',
      avatarUrl: '',
      title: 'Developer',
      location: 'Berlin, Germany',
      links: {
        website: 'https://mikesmith.com',
        twitter: 'https://twitter.com/mikesmith',
        instagram: 'https://instagram.com/mikesmith',
        linkedIn: 'https://linkedin.com/in/mikesmith',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 5,
      fullName: 'Yuki Martinez',
      username: 'yukimartinez',
      email: 'yukimartinez@example.com',
      avatarUrl: '',
      title: 'COO',
      location: 'New York, NY',
      links: {
        website: 'https://yukimartinez.com',
        twitter: 'https://twitter.com/yukimartinez',
        instagram: 'https://instagram.com/yukimartinez',
        linkedIn: 'https://linkedin.com/in/yukimartinez',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 6,
      fullName: 'Mike Smith',
      username: 'mikesmith',
      email: 'mikesmith@example.com',
      avatarUrl: '',
      title: 'Developer',
      location: 'Berlin, Germany',
      links: {
        website: 'https://mikesmith.com',
        twitter: 'https://twitter.com/mikesmith',
        instagram: 'https://instagram.com/mikesmith',
        linkedIn: 'https://linkedin.com/in/mikesmith',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 7,
      fullName: 'Yuki Martinez',
      username: 'yukimartinez',
      email: 'yukimartinez@example.com',
      avatarUrl: '',
      title: 'Graphic Designer',
      location: 'Tokyo, Japan',
      links: {
        website: 'https://yukimartinez.com',
        twitter: 'https://twitter.com/yukimartinez',
        instagram: 'https://instagram.com/yukimartinez',
        linkedIn: 'https://linkedin.com/in/yukimartinez',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 8,
      fullName: 'Carlos Smith',
      username: 'carlossmith',
      email: 'carlossmith@example.com',
      avatarUrl: '',
      title: 'Product Manager',
      location: 'Berlin, Germany',
      links: {
        website: 'https://carlossmith.com',
        twitter: 'https://twitter.com/carlossmith',
        instagram: 'https://instagram.com/carlossmith',
        linkedIn: 'https://linkedin.com/in/carlossmith',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 9,
      fullName: 'Eve Lee',
      username: 'evelee',
      email: 'evelee@example.com',
      avatarUrl: '',
      title: 'Product Manager',
      location: 'San Francisco, CA',
      links: {
        website: 'https://evelee.com',
        twitter: 'https://twitter.com/evelee',
        instagram: 'https://instagram.com/evelee',
        linkedIn: 'https://linkedin.com/in/evelee',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 10,
      fullName: 'Maria Martinez',
      username: 'mariamartinez',
      email: 'mariamartinez@example.com',
      avatarUrl: '',
      title: 'CEO',
      location: 'Berlin, Germany',
      links: {
        website: 'https://mariamartinez.com',
        twitter: 'https://twitter.com/mariamartinez',
        instagram: 'https://instagram.com/mariamartinez',
        linkedIn: 'https://linkedin.com/in/mariamartinez',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 11,
      fullName: 'Alice Brown',
      username: 'alicebrown',
      email: 'alicebrown@example.com',
      avatarUrl: '',
      title: 'COO',
      location: 'Tokyo, Japan',
      links: {
        website: 'https://alicebrown.com',
        twitter: 'https://twitter.com/alicebrown',
        instagram: 'https://instagram.com/alicebrown',
        linkedIn: 'https://linkedin.com/in/alicebrown',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 12,
      fullName: 'Jane Johnson',
      username: 'janejohnson',
      email: 'janejohnson@example.com',
      avatarUrl: '',
      title: 'Graphic Designer',
      location: 'Berlin, Germany',
      links: {
        website: 'https://janejohnson.com',
        twitter: 'https://twitter.com/janejohnson',
        instagram: 'https://instagram.com/janejohnson',
        linkedIn: 'https://linkedin.com/in/janejohnson',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 13,
      fullName: 'Eve Miller',
      username: 'evemiller',
      email: 'evemiller@example.com',
      avatarUrl: '',
      title: 'Graphic Designer',
      location: 'Sao Paulo, Brazil',
      links: {
        website: 'https://evemiller.com',
        twitter: 'https://twitter.com/evemiller',
        instagram: 'https://instagram.com/evemiller',
        linkedIn: 'https://linkedin.com/in/evemiller',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 14,
      fullName: 'Jane Davis',
      username: 'janedavis',
      email: 'janedavis@example.com',
      avatarUrl: '',
      title: 'CEO',
      location: 'Tokyo, Japan',
      links: {
        website: 'https://janedavis.com',
        twitter: 'https://twitter.com/janedavis',
        instagram: 'https://instagram.com/janedavis',
        linkedIn: 'https://linkedin.com/in/janedavis',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 15,
      fullName: 'Jane Doe',
      username: 'janedoe',
      email: 'janedoe@example.com',
      avatarUrl: '',
      title: 'CEO',
      location: 'Sao Paulo, Brazil',
      links: {
        website: 'https://janedoe.com',
        twitter: 'https://twitter.com/janedoe',
        instagram: 'https://instagram.com/janedoe',
        linkedIn: 'https://linkedin.com/in/janedoe',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 16,
      fullName: 'Jane Lee',
      username: 'janelee',
      email: 'janelee@example.com',
      avatarUrl: '',
      title: 'COO',
      location: 'Tokyo, Japan',
      links: {
        website: 'https://janelee.com',
        twitter: 'https://twitter.com/janelee',
        instagram: 'https://instagram.com/janelee',
        linkedIn: 'https://linkedin.com/in/janelee',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 17,
      fullName: 'Bob Lee',
      username: 'boblee',
      email: 'boblee@example.com',
      avatarUrl: '',
      title: 'Developer',
      location: 'Berlin, Germany',
      links: {
        website: 'https://boblee.com',
        twitter: 'https://twitter.com/boblee',
        instagram: 'https://instagram.com/boblee',
        linkedIn: 'https://linkedin.com/in/boblee',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 18,
      fullName: 'John Davis',
      username: 'johndavis',
      email: 'johndavis@example.com',
      avatarUrl: '',
      title: 'COO',
      location: 'Tokyo, Japan',
      links: {
        website: 'https://johndavis.com',
        twitter: 'https://twitter.com/johndavis',
        instagram: 'https://instagram.com/johndavis',
        linkedIn: 'https://linkedin.com/in/johndavis',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 19,
      fullName: 'Eve Garcia',
      username: 'evegarcia',
      email: 'evegarcia@example.com',
      avatarUrl: '',
      title: 'COO',
      location: 'San Francisco, CA',
      links: {
        website: 'https://evegarcia.com',
        twitter: 'https://twitter.com/evegarcia',
        instagram: 'https://instagram.com/evegarcia',
        linkedIn: 'https://linkedin.com/in/evegarcia',
      },
      subscribers: [],
      subscribedTo: [],
    },
    {
      id: 20,
      fullName: 'Yuki Brown',
      username: 'yukibrown',
      email: 'yukibrown@example.com',
      avatarUrl: '',
      title: 'Graphic Designer',
      location: 'Berlin, Germany',
      links: {
        website: 'https://yukibrown.com',
        twitter: 'https://twitter.com/yukibrown',
        instagram: 'https://instagram.com/yukibrown',
        linkedIn: 'https://linkedin.com/in/yukibrown',
      },
      subscribers: [],
      subscribedTo: [],
    },
  ],
  backers_notifications: [
    {
      id: 1,
      user: {
        id: 7,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 207,
      date: '2024-04-05T00:00:00',
    },
    {
      id: 2,
      user: {
        id: 5,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'New York, NY',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 374,
      date: '2024-01-07T00:00:00',
    },
    {
      id: 3,
      user: {
        id: 8,
        fullName: 'Carlos Smith',
        username: 'carlossmith',
        email: 'carlossmith@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'Berlin, Germany',
        links: {
          website: 'https://carlossmith.com',
          twitter: 'https://twitter.com/carlossmith',
          instagram: 'https://instagram.com/carlossmith',
          linkedIn: 'https://linkedin.com/in/carlossmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 277,
      date: '2024-10-28T00:00:00',
    },
    {
      id: 4,
      user: {
        id: 20,
        fullName: 'Yuki Brown',
        username: 'yukibrown',
        email: 'yukibrown@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://yukibrown.com',
          twitter: 'https://twitter.com/yukibrown',
          instagram: 'https://instagram.com/yukibrown',
          linkedIn: 'https://linkedin.com/in/yukibrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 435,
      date: '2024-03-05T00:00:00',
    },
    {
      id: 5,
      user: {
        id: 14,
        fullName: 'Jane Davis',
        username: 'janedavis',
        email: 'janedavis@example.com',
        avatarUrl: '',
        title: 'CEO',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://janedavis.com',
          twitter: 'https://twitter.com/janedavis',
          instagram: 'https://instagram.com/janedavis',
          linkedIn: 'https://linkedin.com/in/janedavis',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 124,
      date: '2024-10-03T00:00:00',
    },
    {
      id: 6,
      user: {
        id: 20,
        fullName: 'Yuki Brown',
        username: 'yukibrown',
        email: 'yukibrown@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://yukibrown.com',
          twitter: 'https://twitter.com/yukibrown',
          instagram: 'https://instagram.com/yukibrown',
          linkedIn: 'https://linkedin.com/in/yukibrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 291,
      date: '2024-07-28T00:00:00',
    },
    {
      id: 7,
      user: {
        id: 6,
        fullName: 'Mike Smith',
        username: 'mikesmith',
        email: 'mikesmith@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://mikesmith.com',
          twitter: 'https://twitter.com/mikesmith',
          instagram: 'https://instagram.com/mikesmith',
          linkedIn: 'https://linkedin.com/in/mikesmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 184,
      date: '2024-12-20T00:00:00',
    },
    {
      id: 8,
      user: {
        id: 9,
        fullName: 'Eve Lee',
        username: 'evelee',
        email: 'evelee@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'San Francisco, CA',
        links: {
          website: 'https://evelee.com',
          twitter: 'https://twitter.com/evelee',
          instagram: 'https://instagram.com/evelee',
          linkedIn: 'https://linkedin.com/in/evelee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 141,
      date: '2024-05-11T00:00:00',
    },
    {
      id: 9,
      user: {
        id: 2,
        fullName: 'John Garcia',
        username: 'johngarcia',
        email: 'johngarcia@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'San Francisco, CA',
        links: {
          website: 'https://johngarcia.com',
          twitter: 'https://twitter.com/johngarcia',
          instagram: 'https://instagram.com/johngarcia',
          linkedIn: 'https://linkedin.com/in/johngarcia',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 25,
      date: '2024-03-25T00:00:00',
    },
    {
      id: 10,
      user: {
        id: 9,
        fullName: 'Eve Lee',
        username: 'evelee',
        email: 'evelee@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'San Francisco, CA',
        links: {
          website: 'https://evelee.com',
          twitter: 'https://twitter.com/evelee',
          instagram: 'https://instagram.com/evelee',
          linkedIn: 'https://linkedin.com/in/evelee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 135,
      date: '2024-02-07T00:00:00',
    },
    {
      id: 11,
      user: {
        id: 11,
        fullName: 'Alice Brown',
        username: 'alicebrown',
        email: 'alicebrown@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://alicebrown.com',
          twitter: 'https://twitter.com/alicebrown',
          instagram: 'https://instagram.com/alicebrown',
          linkedIn: 'https://linkedin.com/in/alicebrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 460,
      date: '2024-04-28T00:00:00',
    },
    {
      id: 12,
      user: {
        id: 20,
        fullName: 'Yuki Brown',
        username: 'yukibrown',
        email: 'yukibrown@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://yukibrown.com',
          twitter: 'https://twitter.com/yukibrown',
          instagram: 'https://instagram.com/yukibrown',
          linkedIn: 'https://linkedin.com/in/yukibrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 407,
      date: '2024-02-20T00:00:00',
    },
    {
      id: 13,
      user: {
        id: 11,
        fullName: 'Alice Brown',
        username: 'alicebrown',
        email: 'alicebrown@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://alicebrown.com',
          twitter: 'https://twitter.com/alicebrown',
          instagram: 'https://instagram.com/alicebrown',
          linkedIn: 'https://linkedin.com/in/alicebrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 162,
      date: '2024-05-02T00:00:00',
    },
    {
      id: 14,
      user: {
        id: 13,
        fullName: 'Eve Miller',
        username: 'evemiller',
        email: 'evemiller@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://evemiller.com',
          twitter: 'https://twitter.com/evemiller',
          instagram: 'https://instagram.com/evemiller',
          linkedIn: 'https://linkedin.com/in/evemiller',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 442,
      date: '2024-06-19T00:00:00',
    },
    {
      id: 15,
      user: {
        id: 1,
        fullName: 'John Smith',
        username: 'johnsmith',
        email: 'johnsmith@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'New York, NY',
        links: {
          website: 'https://johnsmith.com',
          twitter: 'https://twitter.com/johnsmith',
          instagram: 'https://instagram.com/johnsmith',
          linkedIn: 'https://linkedin.com/in/johnsmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 151,
      date: '2024-06-23T00:00:00',
    },
    {
      id: 16,
      user: {
        id: 12,
        fullName: 'Jane Johnson',
        username: 'janejohnson',
        email: 'janejohnson@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://janejohnson.com',
          twitter: 'https://twitter.com/janejohnson',
          instagram: 'https://instagram.com/janejohnson',
          linkedIn: 'https://linkedin.com/in/janejohnson',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 495,
      date: '2024-02-23T00:00:00',
    },
    {
      id: 17,
      user: {
        id: 13,
        fullName: 'Eve Miller',
        username: 'evemiller',
        email: 'evemiller@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://evemiller.com',
          twitter: 'https://twitter.com/evemiller',
          instagram: 'https://instagram.com/evemiller',
          linkedIn: 'https://linkedin.com/in/evemiller',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 420,
      date: '2024-04-22T00:00:00',
    },
    {
      id: 18,
      user: {
        id: 13,
        fullName: 'Eve Miller',
        username: 'evemiller',
        email: 'evemiller@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://evemiller.com',
          twitter: 'https://twitter.com/evemiller',
          instagram: 'https://instagram.com/evemiller',
          linkedIn: 'https://linkedin.com/in/evemiller',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 282,
      date: '2024-10-16T00:00:00',
    },
    {
      id: 19,
      user: {
        id: 7,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 115,
      date: '2024-11-27T00:00:00',
    },
    {
      id: 20,
      user: {
        id: 20,
        fullName: 'Yuki Brown',
        username: 'yukibrown',
        email: 'yukibrown@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://yukibrown.com',
          twitter: 'https://twitter.com/yukibrown',
          instagram: 'https://instagram.com/yukibrown',
          linkedIn: 'https://linkedin.com/in/yukibrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      amount: 144,
      date: '2024-04-11T00:00:00',
    },
  ],
  subscription_notifications: [
    {
      id: 1,
      user: {
        id: 12,
        fullName: 'Jane Johnson',
        username: 'janejohnson',
        email: 'janejohnson@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://janejohnson.com',
          twitter: 'https://twitter.com/janejohnson',
          instagram: 'https://instagram.com/janejohnson',
          linkedIn: 'https://linkedin.com/in/janejohnson',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-03-21T00:00:00',
    },
    {
      id: 2,
      user: {
        id: 8,
        fullName: 'Carlos Smith',
        username: 'carlossmith',
        email: 'carlossmith@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'Berlin, Germany',
        links: {
          website: 'https://carlossmith.com',
          twitter: 'https://twitter.com/carlossmith',
          instagram: 'https://instagram.com/carlossmith',
          linkedIn: 'https://linkedin.com/in/carlossmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-12-15T00:00:00',
    },
    {
      id: 3,
      user: {
        id: 19,
        fullName: 'Eve Garcia',
        username: 'evegarcia',
        email: 'evegarcia@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'San Francisco, CA',
        links: {
          website: 'https://evegarcia.com',
          twitter: 'https://twitter.com/evegarcia',
          instagram: 'https://instagram.com/evegarcia',
          linkedIn: 'https://linkedin.com/in/evegarcia',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-04-10T00:00:00',
    },
    {
      id: 4,
      user: {
        id: 4,
        fullName: 'Mike Smith',
        username: 'mikesmith',
        email: 'mikesmith@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://mikesmith.com',
          twitter: 'https://twitter.com/mikesmith',
          instagram: 'https://instagram.com/mikesmith',
          linkedIn: 'https://linkedin.com/in/mikesmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-02-02T00:00:00',
    },
    {
      id: 5,
      user: {
        id: 17,
        fullName: 'Bob Lee',
        username: 'boblee',
        email: 'boblee@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://boblee.com',
          twitter: 'https://twitter.com/boblee',
          instagram: 'https://instagram.com/boblee',
          linkedIn: 'https://linkedin.com/in/boblee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-09-23T00:00:00',
    },
    {
      id: 6,
      user: {
        id: 13,
        fullName: 'Eve Miller',
        username: 'evemiller',
        email: 'evemiller@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://evemiller.com',
          twitter: 'https://twitter.com/evemiller',
          instagram: 'https://instagram.com/evemiller',
          linkedIn: 'https://linkedin.com/in/evemiller',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-06-16T00:00:00',
    },
    {
      id: 7,
      user: {
        id: 15,
        fullName: 'Jane Doe',
        username: 'janedoe',
        email: 'janedoe@example.com',
        avatarUrl: '',
        title: 'CEO',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://janedoe.com',
          twitter: 'https://twitter.com/janedoe',
          instagram: 'https://instagram.com/janedoe',
          linkedIn: 'https://linkedin.com/in/janedoe',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-04-22T00:00:00',
    },
    {
      id: 8,
      user: {
        id: 13,
        fullName: 'Eve Miller',
        username: 'evemiller',
        email: 'evemiller@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://evemiller.com',
          twitter: 'https://twitter.com/evemiller',
          instagram: 'https://instagram.com/evemiller',
          linkedIn: 'https://linkedin.com/in/evemiller',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-03-16T00:00:00',
    },
    {
      id: 9,
      user: {
        id: 1,
        fullName: 'John Smith',
        username: 'johnsmith',
        email: 'johnsmith@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'New York, NY',
        links: {
          website: 'https://johnsmith.com',
          twitter: 'https://twitter.com/johnsmith',
          instagram: 'https://instagram.com/johnsmith',
          linkedIn: 'https://linkedin.com/in/johnsmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-05-05T00:00:00',
    },
    {
      id: 10,
      user: {
        id: 17,
        fullName: 'Bob Lee',
        username: 'boblee',
        email: 'boblee@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://boblee.com',
          twitter: 'https://twitter.com/boblee',
          instagram: 'https://instagram.com/boblee',
          linkedIn: 'https://linkedin.com/in/boblee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-01-16T00:00:00',
    },
    {
      id: 11,
      user: {
        id: 9,
        fullName: 'Eve Lee',
        username: 'evelee',
        email: 'evelee@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'San Francisco, CA',
        links: {
          website: 'https://evelee.com',
          twitter: 'https://twitter.com/evelee',
          instagram: 'https://instagram.com/evelee',
          linkedIn: 'https://linkedin.com/in/evelee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-03-12T00:00:00',
    },
    {
      id: 12,
      user: {
        id: 5,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'New York, NY',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-01-15T00:00:00',
    },
    {
      id: 13,
      user: {
        id: 2,
        fullName: 'John Garcia',
        username: 'johngarcia',
        email: 'johngarcia@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'San Francisco, CA',
        links: {
          website: 'https://johngarcia.com',
          twitter: 'https://twitter.com/johngarcia',
          instagram: 'https://instagram.com/johngarcia',
          linkedIn: 'https://linkedin.com/in/johngarcia',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-04-08T00:00:00',
    },
    {
      id: 14,
      user: {
        id: 15,
        fullName: 'Jane Doe',
        username: 'janedoe',
        email: 'janedoe@example.com',
        avatarUrl: '',
        title: 'CEO',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://janedoe.com',
          twitter: 'https://twitter.com/janedoe',
          instagram: 'https://instagram.com/janedoe',
          linkedIn: 'https://linkedin.com/in/janedoe',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-08-11T00:00:00',
    },
    {
      id: 15,
      user: {
        id: 5,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'New York, NY',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-11-13T00:00:00',
    },
    {
      id: 16,
      user: {
        id: 5,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'New York, NY',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-11-16T00:00:00',
    },
    {
      id: 17,
      user: {
        id: 5,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'New York, NY',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-04-07T00:00:00',
    },
    {
      id: 18,
      user: {
        id: 11,
        fullName: 'Alice Brown',
        username: 'alicebrown',
        email: 'alicebrown@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://alicebrown.com',
          twitter: 'https://twitter.com/alicebrown',
          instagram: 'https://instagram.com/alicebrown',
          linkedIn: 'https://linkedin.com/in/alicebrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-12-09T00:00:00',
    },
    {
      id: 19,
      user: {
        id: 2,
        fullName: 'John Garcia',
        username: 'johngarcia',
        email: 'johngarcia@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'San Francisco, CA',
        links: {
          website: 'https://johngarcia.com',
          twitter: 'https://twitter.com/johngarcia',
          instagram: 'https://instagram.com/johngarcia',
          linkedIn: 'https://linkedin.com/in/johngarcia',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-11-06T00:00:00',
    },
    {
      id: 20,
      user: {
        id: 15,
        fullName: 'Jane Doe',
        username: 'janedoe',
        email: 'janedoe@example.com',
        avatarUrl: '',
        title: 'CEO',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://janedoe.com',
          twitter: 'https://twitter.com/janedoe',
          instagram: 'https://instagram.com/janedoe',
          linkedIn: 'https://linkedin.com/in/janedoe',
        },
        subscribers: [],
        subscribedTo: [],
      },
      date: '2024-10-15T00:00:00',
    },
  ],
  notifications: [
    {
      id: 1,
      notificationType: 'backers',
      user: {
        id: 20,
        fullName: 'Yuki Brown',
        username: 'yukibrown',
        email: 'yukibrown@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://yukibrown.com',
          twitter: 'https://twitter.com/yukibrown',
          instagram: 'https://instagram.com/yukibrown',
          linkedIn: 'https://linkedin.com/in/yukibrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 2,
      createdDate: '2024-03-05T00:00:00',
    },
    {
      id: 2,
      notificationType: 'backers',
      user: {
        id: 16,
        fullName: 'Jane Lee',
        username: 'janelee',
        email: 'janelee@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://janelee.com',
          twitter: 'https://twitter.com/janelee',
          instagram: 'https://instagram.com/janelee',
          linkedIn: 'https://linkedin.com/in/janelee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 13,
      createdDate: '2024-04-04T00:00:00',
    },
    {
      id: 3,
      notificationType: 'subscription',
      user: {
        id: 3,
        fullName: 'Bob Smith',
        username: 'bobsmith',
        email: 'bobsmith@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://bobsmith.com',
          twitter: 'https://twitter.com/bobsmith',
          instagram: 'https://instagram.com/bobsmith',
          linkedIn: 'https://linkedin.com/in/bobsmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 15,
      createdDate: '2024-06-28T00:00:00',
    },
    {
      id: 4,
      notificationType: 'subscription',
      user: {
        id: 12,
        fullName: 'Jane Johnson',
        username: 'janejohnson',
        email: 'janejohnson@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://janejohnson.com',
          twitter: 'https://twitter.com/janejohnson',
          instagram: 'https://instagram.com/janejohnson',
          linkedIn: 'https://linkedin.com/in/janejohnson',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 16,
      createdDate: '2024-04-18T00:00:00',
    },
    {
      id: 5,
      notificationType: 'backers',
      user: {
        id: 17,
        fullName: 'Bob Lee',
        username: 'boblee',
        email: 'boblee@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://boblee.com',
          twitter: 'https://twitter.com/boblee',
          instagram: 'https://instagram.com/boblee',
          linkedIn: 'https://linkedin.com/in/boblee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 20,
      createdDate: '2024-12-19T00:00:00',
    },
    {
      id: 6,
      notificationType: 'subscription',
      user: {
        id: 19,
        fullName: 'Eve Garcia',
        username: 'evegarcia',
        email: 'evegarcia@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'San Francisco, CA',
        links: {
          website: 'https://evegarcia.com',
          twitter: 'https://twitter.com/evegarcia',
          instagram: 'https://instagram.com/evegarcia',
          linkedIn: 'https://linkedin.com/in/evegarcia',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 9,
      createdDate: '2024-10-13T00:00:00',
    },
    {
      id: 7,
      notificationType: 'backers',
      user: {
        id: 20,
        fullName: 'Yuki Brown',
        username: 'yukibrown',
        email: 'yukibrown@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://yukibrown.com',
          twitter: 'https://twitter.com/yukibrown',
          instagram: 'https://instagram.com/yukibrown',
          linkedIn: 'https://linkedin.com/in/yukibrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 4,
      createdDate: '2024-08-18T00:00:00',
    },
    {
      id: 8,
      notificationType: 'backers',
      user: {
        id: 17,
        fullName: 'Bob Lee',
        username: 'boblee',
        email: 'boblee@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://boblee.com',
          twitter: 'https://twitter.com/boblee',
          instagram: 'https://instagram.com/boblee',
          linkedIn: 'https://linkedin.com/in/boblee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 16,
      createdDate: '2024-07-18T00:00:00',
    },
    {
      id: 9,
      notificationType: 'subscription',
      user: {
        id: 8,
        fullName: 'Carlos Smith',
        username: 'carlossmith',
        email: 'carlossmith@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'Berlin, Germany',
        links: {
          website: 'https://carlossmith.com',
          twitter: 'https://twitter.com/carlossmith',
          instagram: 'https://instagram.com/carlossmith',
          linkedIn: 'https://linkedin.com/in/carlossmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 3,
      createdDate: '2024-05-10T00:00:00',
    },
    {
      id: 10,
      notificationType: 'backers',
      user: {
        id: 10,
        fullName: 'Maria Martinez',
        username: 'mariamartinez',
        email: 'mariamartinez@example.com',
        avatarUrl: '',
        title: 'CEO',
        location: 'Berlin, Germany',
        links: {
          website: 'https://mariamartinez.com',
          twitter: 'https://twitter.com/mariamartinez',
          instagram: 'https://instagram.com/mariamartinez',
          linkedIn: 'https://linkedin.com/in/mariamartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 2,
      createdDate: '2024-11-28T00:00:00',
    },
    {
      id: 11,
      notificationType: 'subscription',
      user: {
        id: 6,
        fullName: 'Mike Smith',
        username: 'mikesmith',
        email: 'mikesmith@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://mikesmith.com',
          twitter: 'https://twitter.com/mikesmith',
          instagram: 'https://instagram.com/mikesmith',
          linkedIn: 'https://linkedin.com/in/mikesmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 18,
      createdDate: '2024-12-22T00:00:00',
    },
    {
      id: 12,
      notificationType: 'subscription',
      user: {
        id: 16,
        fullName: 'Jane Lee',
        username: 'janelee',
        email: 'janelee@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://janelee.com',
          twitter: 'https://twitter.com/janelee',
          instagram: 'https://instagram.com/janelee',
          linkedIn: 'https://linkedin.com/in/janelee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 13,
      createdDate: '2024-08-01T00:00:00',
    },
    {
      id: 13,
      notificationType: 'backers',
      user: {
        id: 10,
        fullName: 'Maria Martinez',
        username: 'mariamartinez',
        email: 'mariamartinez@example.com',
        avatarUrl: '',
        title: 'CEO',
        location: 'Berlin, Germany',
        links: {
          website: 'https://mariamartinez.com',
          twitter: 'https://twitter.com/mariamartinez',
          instagram: 'https://instagram.com/mariamartinez',
          linkedIn: 'https://linkedin.com/in/mariamartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 12,
      createdDate: '2024-11-03T00:00:00',
    },
    {
      id: 14,
      notificationType: 'subscription',
      user: {
        id: 1,
        fullName: 'John Smith',
        username: 'johnsmith',
        email: 'johnsmith@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'New York, NY',
        links: {
          website: 'https://johnsmith.com',
          twitter: 'https://twitter.com/johnsmith',
          instagram: 'https://instagram.com/johnsmith',
          linkedIn: 'https://linkedin.com/in/johnsmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 11,
      createdDate: '2024-03-10T00:00:00',
    },
    {
      id: 15,
      notificationType: 'backers',
      user: {
        id: 8,
        fullName: 'Carlos Smith',
        username: 'carlossmith',
        email: 'carlossmith@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'Berlin, Germany',
        links: {
          website: 'https://carlossmith.com',
          twitter: 'https://twitter.com/carlossmith',
          instagram: 'https://instagram.com/carlossmith',
          linkedIn: 'https://linkedin.com/in/carlossmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 4,
      createdDate: '2024-07-03T00:00:00',
    },
    {
      id: 16,
      notificationType: 'backers',
      user: {
        id: 1,
        fullName: 'John Smith',
        username: 'johnsmith',
        email: 'johnsmith@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'New York, NY',
        links: {
          website: 'https://johnsmith.com',
          twitter: 'https://twitter.com/johnsmith',
          instagram: 'https://instagram.com/johnsmith',
          linkedIn: 'https://linkedin.com/in/johnsmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 7,
      createdDate: '2024-09-15T00:00:00',
    },
    {
      id: 17,
      notificationType: 'subscription',
      user: {
        id: 7,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 12,
      createdDate: '2024-03-06T00:00:00',
    },
    {
      id: 18,
      notificationType: 'subscription',
      user: {
        id: 13,
        fullName: 'Eve Miller',
        username: 'evemiller',
        email: 'evemiller@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://evemiller.com',
          twitter: 'https://twitter.com/evemiller',
          instagram: 'https://instagram.com/evemiller',
          linkedIn: 'https://linkedin.com/in/evemiller',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 6,
      createdDate: '2024-11-18T00:00:00',
    },
    {
      id: 19,
      notificationType: 'backers',
      user: {
        id: 9,
        fullName: 'Eve Lee',
        username: 'evelee',
        email: 'evelee@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'San Francisco, CA',
        links: {
          website: 'https://evelee.com',
          twitter: 'https://twitter.com/evelee',
          instagram: 'https://instagram.com/evelee',
          linkedIn: 'https://linkedin.com/in/evelee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 4,
      createdDate: '2024-03-13T00:00:00',
    },
    {
      id: 20,
      notificationType: 'subscription',
      user: {
        id: 13,
        fullName: 'Eve Miller',
        username: 'evemiller',
        email: 'evemiller@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://evemiller.com',
          twitter: 'https://twitter.com/evemiller',
          instagram: 'https://instagram.com/evemiller',
          linkedIn: 'https://linkedin.com/in/evemiller',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 4,
      createdDate: '2024-05-13T00:00:00',
    },
    {
      id: 21,
      notificationType: 'subscription',
      user: {
        id: 5,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'New York, NY',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 5,
      createdDate: '2024-05-11T00:00:00',
    },
    {
      id: 22,
      notificationType: 'backers',
      user: {
        id: 13,
        fullName: 'Eve Miller',
        username: 'evemiller',
        email: 'evemiller@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://evemiller.com',
          twitter: 'https://twitter.com/evemiller',
          instagram: 'https://instagram.com/evemiller',
          linkedIn: 'https://linkedin.com/in/evemiller',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 5,
      createdDate: '2024-09-22T00:00:00',
    },
    {
      id: 23,
      notificationType: 'subscription',
      user: {
        id: 2,
        fullName: 'John Garcia',
        username: 'johngarcia',
        email: 'johngarcia@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'San Francisco, CA',
        links: {
          website: 'https://johngarcia.com',
          twitter: 'https://twitter.com/johngarcia',
          instagram: 'https://instagram.com/johngarcia',
          linkedIn: 'https://linkedin.com/in/johngarcia',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 20,
      createdDate: '2024-12-07T00:00:00',
    },
    {
      id: 24,
      notificationType: 'backers',
      user: {
        id: 7,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 18,
      createdDate: '2024-07-28T00:00:00',
    },
    {
      id: 25,
      notificationType: 'subscription',
      user: {
        id: 19,
        fullName: 'Eve Garcia',
        username: 'evegarcia',
        email: 'evegarcia@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'San Francisco, CA',
        links: {
          website: 'https://evegarcia.com',
          twitter: 'https://twitter.com/evegarcia',
          instagram: 'https://instagram.com/evegarcia',
          linkedIn: 'https://linkedin.com/in/evegarcia',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 12,
      createdDate: '2024-03-10T00:00:00',
    },
    {
      id: 26,
      notificationType: 'backers',
      user: {
        id: 17,
        fullName: 'Bob Lee',
        username: 'boblee',
        email: 'boblee@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://boblee.com',
          twitter: 'https://twitter.com/boblee',
          instagram: 'https://instagram.com/boblee',
          linkedIn: 'https://linkedin.com/in/boblee',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 1,
      createdDate: '2024-05-23T00:00:00',
    },
    {
      id: 27,
      notificationType: 'backers',
      user: {
        id: 5,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'New York, NY',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 17,
      createdDate: '2024-06-06T00:00:00',
    },
    {
      id: 28,
      notificationType: 'subscription',
      user: {
        id: 3,
        fullName: 'Bob Smith',
        username: 'bobsmith',
        email: 'bobsmith@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://bobsmith.com',
          twitter: 'https://twitter.com/bobsmith',
          instagram: 'https://instagram.com/bobsmith',
          linkedIn: 'https://linkedin.com/in/bobsmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 14,
      createdDate: '2024-01-13T00:00:00',
    },
    {
      id: 29,
      notificationType: 'subscription',
      user: {
        id: 1,
        fullName: 'John Smith',
        username: 'johnsmith',
        email: 'johnsmith@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'New York, NY',
        links: {
          website: 'https://johnsmith.com',
          twitter: 'https://twitter.com/johnsmith',
          instagram: 'https://instagram.com/johnsmith',
          linkedIn: 'https://linkedin.com/in/johnsmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 7,
      createdDate: '2024-08-07T00:00:00',
    },
    {
      id: 30,
      notificationType: 'subscription',
      user: {
        id: 10,
        fullName: 'Maria Martinez',
        username: 'mariamartinez',
        email: 'mariamartinez@example.com',
        avatarUrl: '',
        title: 'CEO',
        location: 'Berlin, Germany',
        links: {
          website: 'https://mariamartinez.com',
          twitter: 'https://twitter.com/mariamartinez',
          instagram: 'https://instagram.com/mariamartinez',
          linkedIn: 'https://linkedin.com/in/mariamartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 8,
      createdDate: '2024-02-16T00:00:00',
    },
    {
      id: 31,
      notificationType: 'backers',
      user: {
        id: 7,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 4,
      createdDate: '2024-03-22T00:00:00',
    },
    {
      id: 32,
      notificationType: 'subscription',
      user: {
        id: 20,
        fullName: 'Yuki Brown',
        username: 'yukibrown',
        email: 'yukibrown@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://yukibrown.com',
          twitter: 'https://twitter.com/yukibrown',
          instagram: 'https://instagram.com/yukibrown',
          linkedIn: 'https://linkedin.com/in/yukibrown',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 3,
      createdDate: '2024-07-01T00:00:00',
    },
    {
      id: 33,
      notificationType: 'subscription',
      user: {
        id: 2,
        fullName: 'John Garcia',
        username: 'johngarcia',
        email: 'johngarcia@example.com',
        avatarUrl: '',
        title: 'Product Manager',
        location: 'San Francisco, CA',
        links: {
          website: 'https://johngarcia.com',
          twitter: 'https://twitter.com/johngarcia',
          instagram: 'https://instagram.com/johngarcia',
          linkedIn: 'https://linkedin.com/in/johngarcia',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 13,
      createdDate: '2024-10-26T00:00:00',
    },
    {
      id: 34,
      notificationType: 'backers',
      user: {
        id: 5,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'New York, NY',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 13,
      createdDate: '2024-10-14T00:00:00',
    },
    {
      id: 35,
      notificationType: 'subscription',
      user: {
        id: 1,
        fullName: 'John Smith',
        username: 'johnsmith',
        email: 'johnsmith@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'New York, NY',
        links: {
          website: 'https://johnsmith.com',
          twitter: 'https://twitter.com/johnsmith',
          instagram: 'https://instagram.com/johnsmith',
          linkedIn: 'https://linkedin.com/in/johnsmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 10,
      createdDate: '2024-07-17T00:00:00',
    },
    {
      id: 36,
      notificationType: 'backers',
      user: {
        id: 4,
        fullName: 'Mike Smith',
        username: 'mikesmith',
        email: 'mikesmith@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://mikesmith.com',
          twitter: 'https://twitter.com/mikesmith',
          instagram: 'https://instagram.com/mikesmith',
          linkedIn: 'https://linkedin.com/in/mikesmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 10,
      createdDate: '2024-01-07T00:00:00',
    },
    {
      id: 37,
      notificationType: 'backers',
      user: {
        id: 7,
        fullName: 'Yuki Martinez',
        username: 'yukimartinez',
        email: 'yukimartinez@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://yukimartinez.com',
          twitter: 'https://twitter.com/yukimartinez',
          instagram: 'https://instagram.com/yukimartinez',
          linkedIn: 'https://linkedin.com/in/yukimartinez',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 16,
      createdDate: '2024-11-22T00:00:00',
    },
    {
      id: 38,
      notificationType: 'backers',
      user: {
        id: 18,
        fullName: 'John Davis',
        username: 'johndavis',
        email: 'johndavis@example.com',
        avatarUrl: '',
        title: 'COO',
        location: 'Tokyo, Japan',
        links: {
          website: 'https://johndavis.com',
          twitter: 'https://twitter.com/johndavis',
          instagram: 'https://instagram.com/johndavis',
          linkedIn: 'https://linkedin.com/in/johndavis',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 1,
      createdDate: '2024-10-28T00:00:00',
    },
    {
      id: 39,
      notificationType: 'backers',
      user: {
        id: 6,
        fullName: 'Mike Smith',
        username: 'mikesmith',
        email: 'mikesmith@example.com',
        avatarUrl: '',
        title: 'Developer',
        location: 'Berlin, Germany',
        links: {
          website: 'https://mikesmith.com',
          twitter: 'https://twitter.com/mikesmith',
          instagram: 'https://instagram.com/mikesmith',
          linkedIn: 'https://linkedin.com/in/mikesmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 1,
      createdDate: '2024-11-19T00:00:00',
    },
    {
      id: 40,
      notificationType: 'backers',
      user: {
        id: 3,
        fullName: 'Bob Smith',
        username: 'bobsmith',
        email: 'bobsmith@example.com',
        avatarUrl: '',
        title: 'Graphic Designer',
        location: 'Sao Paulo, Brazil',
        links: {
          website: 'https://bobsmith.com',
          twitter: 'https://twitter.com/bobsmith',
          instagram: 'https://instagram.com/bobsmith',
          linkedIn: 'https://linkedin.com/in/bobsmith',
        },
        subscribers: [],
        subscribedTo: [],
      },
      relatedEntityId: 6,
      createdDate: '2024-03-14T00:00:00',
    },
  ],
};
